server:
  port: 8081

spring:
  application:
    name: users-service

  datasource:
    url: jdbc:mysql://localhost:3306/users_db?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # crea/actualiza tablas según tus entidades
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
